# Generated by Django 4.2.4 on 2023-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedcity", old_name="user", new_name="user_id",
        ),
        migrations.AlterField(
            model_name="city", name="latitude", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="city", name="longitude", field=models.FloatField(),
        ),
    ]
